#+title: Data Structure
#+author: Holofunctor   
#+excerpt: This is an example excerpt for the data structure page.
#+date: <2026-03-03, Tue>
#+tags: cs foundation

In this document we recap some basic data structures, choosing the ~C++~ language is out of a sense of nostalgia.

* List

A *list* (or *sequence*) is a finite, ordered collection of elements from a pre-defined set $Sigma$. 

The set of all finite lists over $Sigma$ is $Sigma^* := { Sigma^n|n in NN }$.

The term list is also used for several concrete data structures that can be used to implement abstract lists, especially linked lists and arrays.

** Array

An *array* is a random-access data structure that implements the list ADT. In most programming languages, arrays are stored in contiguous memory with uniform element size.

Modern arrays are typically implemented dynamically. They overcome the fixed capacity of static arrays by resizing the underlying buffer—usually doubling its size—when full and copying existing elements.

#+begin_src julia
    function reserve(new_capacity):
        new_buffer <- new buffer of size `new_cap` 
        for i <- 0 to size - 1 do:
            new_buffer[i] <- buffer[i]
        end
        buffer <- new_buffer
        capacity <- new_capacity

#+end_src

Then in ~append~ and ~insert~:

#+begin_src julia
    if size = capacity:
        reserve(capacity * 2)
#+end_src

Dynamic arrays are a common example when teaching amortized analysis. Consider performing $n$ insertions starting from capacity $m$, the total cost of copying elements during all resizes is
$m sum_(i=1)^(k) 2^i < 2 dot.op 2 (n + m) = Theta (n)$. Dividing by $n$ operations gives that each insertion takes amortized constant time.

The algorithms one may concern regarding arrays are mainly searching and sorting, which will be covered in [[./algorithms#sorting]].

** Linked List

A *linked list* is another implementation of the list ADT such that modifications are $O(1)$ but queries are $O(n)$.

We implement ~list~ as a singly-linked list without any /sentinel/ (or /dummy/) nodes. 

There are variants of circular, doubly-linked lists with one or two sentinel nodes, however, in most of the coding exercises, the list is usually singly-linked and only the pointer ~*head~ to the first node is provided. In such case, pointer manipulations need some extra work.

** Stack

A *stack* is a last-in-first-out (LIFO) sequential data structure.

*** Applications

**** Number System Conversion

**** Stack Permutation

**** Parentheses Matching

**** Backtracking

- Eight queens puzzle
- Maze pathfinding

** Queue

A *queue* is a first-in-first-out (FIFO) sequential data structure.

* Tree 

** Binary Tree

Tree traversal:

    - preorder
    - inorder
    - postorder

*** Huffman coding 

** Binary Search Tree

** Balanced Binary Search Tree

** AVL Tree

** Red-black Tree

** Interval (Segment) Tree

** B-Tree

* Heap (Priority Queue)

* Dictionary

** Skip List

** Hash Table

* Disjoint Set

* Graph

** Forward Star Representaton

    1. BFS, DFS
    2. topological sort
    3. strongly connected component
    4. minimum spanning tree
        - Kruskal-Prim algorithm
    5. single-source shortest path
        - Bellman-Ford algorithm
        - Dijkstra's algorithm
    6. all-pairs shortest path
        - Floyd-Warshall algorithm
        - Johnson's algorithm for sparse graph
    7. maximum flow
    8. bipartite matching
